
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K2rYVZoO5Xr0dn7uJmkBSFz-og-y9R_d
"""

import random

def rock_paper_scissors():
    choices = ['rock', 'paper', 'scissors']
    wins = {'rock': 'scissors', 'paper': 'rock', 'scissors': 'paper'}

    print("✂️ Rock Paper Scissors!")
    score = {'player': 0, 'computer': 0}

    while True:
        player = input("\nYour choice (rock/paper/scissors) or 'quit': ").lower()

        if player == 'quit':
            print(f"\n🏆 Final Score - You: {score['player']}, Computer: {score['computer']}")
            break

        if player not in choices:
            print("❌ Invalid choice!")
            continue

        computer = random.choice(choices)
        print(f"Computer chose: {computer}")

        if player == computer:
            print("🤝 It's a tie!")
        elif wins[player] == computer:
            print("🎉 You win!")
            score['player'] += 1
        else:
            print("😢 Computer wins!")
            score['computer'] += 1

# Run game
rock_paper_scissors()
