# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AuFKfu2o3kMUf_Jl__q9V_Jpd7hgTY8U
"""

def print_board(board):
    print("\n   |   |   ")
    print(f" {board[0]} | {board[1]} | {board[2]} ")
    print("___|___|___")
    print("   |   |   ")
    print(f" {board[3]} | {board[4]} | {board[5]} ")
    print("___|___|___")
    print("   |   |   ")
    print(f" {board[6]} | {board[7]} | {board[8]} ")
    print("   |   |   \n")

def check_winner(board, player):
    wins = [(0,1,2),(3,4,5),(6,7,8),(0,3,6),(1,4,7),(2,5,8),(0,4,8),(2,4,6)]
    return any(board[a] == board[b] == board[c] == player for a,b,c in wins)

def tic_tac_toe():
    board = [' ']*9
    current_player = 'X'

    print("🎮 Tic Tac Toe!")
    print("Positions:")
    print(" 0 | 1 | 2 ")
    print("___|___|___")
    print(" 3 | 4 | 5 ")
    print("___|___|___")
    print(" 6 | 7 | 8 ")

    while True:
        print_board(board)

        try:
            pos = int(input(f"Player {current_player}, choose position (0-8): "))
            if pos not in range(9) or board[pos] != ' ':
                print("❌ Invalid move!")
                continue

            board[pos] = current_player

            if check_winner(board, current_player):
                print_board(board)
                print(f"🎉 Player {current_player} WINS!")
                break

            if ' ' not in board:
                print("🤝 It's a tie!")
                break

            current_player = 'O' if current_player == 'X' else 'X'

        except ValueError:
            print("❌ Enter a number 0-8!")

tic_tac_toe()